# Generated by Django 3.2.7 on 2021-09-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('max_speed', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='цена')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.manufacturer')),
            ],
        ),
    ]
