# Generated by Django 3.2.7 on 2021-10-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_car_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='executors',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
    ]
